### PR TITLE
Do not crash if split URI does not have compared option key

### LINKED ISSUE #8: [Bug] TypeError splitURI[optionKey] is undefined
**Please include the debug file from ~/.config/bowser-gnome@kronosoul.xyz/debug.log**

**Describe the bug**

Links do not open after some time, the `TypeError splitURI[optionKey] is undefined` message is logged.

**To Reproduce**
1. Go in third party app like Thunderbird
2. Click on a link
3. See error in debug.log:

```
(bowser-gnome@kronosoul.xyz) [7/21/2020, 10:59:04 AM]::Info    | User Feedback | Bowser has been Enabled
(bowser-gnome@kronosoul.xyz) [7/21/2020, 10:59:13 AM]:!Error   | () => |
|-TypeError splitURI[optionKey] is undefined
|-Stack Trace:
openBrowser/</<@/home/patrick/.local/share/gnome-shell/extensions/bowser-gnome@kronosoul.xyz/extension.js:172:55
value/<@/home/patrick/.local/share/gnome-shell/extensions/bowser-gnome@kronosoul.xyz/utils.js:61:22
value@/home/patrick/.local/share/gnome-shell/extensions/bowser-gnome@kronosoul.xyz/utils.js:57:30
openBrowser/<@/home/patrick/.local/share/gnome-shell/extensions/bowser-gnome@kronosoul.xyz/extension.js:170:48
value/<@/home/patrick/.local/share/gnome-shell/extensions/bowser-gnome@kronosoul.xyz/utils.js:61:22
value@/home/patrick/.local/share/gnome-shell/extensions/bowser-gnome@kronosoul.xyz/utils.js:57:30
openBrowser@/home/patrick/.local/share/gnome-shell/extensions/bowser-gnome@kronosoul.xyz/extension.js:167:24
processURIs@/home/patrick/.local/share/gnome-shell/extensions/bowser-gnome@kronosoul.xyz/extension.js:154:22
_enableURIWatcher/this.uriListSettingsHandler<@/home/patrick/.local/share/gnome-shell/extensions/bowser-gnome@kronosoul.xyz/extension.js:133:13
```

**Expected behavior**

The link should be opened in a browser.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - Gnome-Shell Version: 3.36.3
 - Browser [e.g. chrome, safari]: Firefox and Chrome
 - Extension Version [e.g. 22]: current master (https://github.com/blipk/bowser-gnome/commit/56666375fde79b9ac616b3b65b2a2ec08e8c375e)

### PR DESCRIPTION
**Pull request by pdecat**
Resolves #8.

### CODE REVIEW

**Comment by pdecat** [comment]
A second part of the fix maybe to address https://github.com/blipk/bowser-gnome/issues/8#issuecomment-661866231:

```
diff --git a/bowser-gnome@kronosoul.xyz/extension.js b/bowser-gnome@kronosoul.xyz/extension.js
index 1335548..7b6e24a 100644
--- a/bowser-gnome@kronosoul.xyz/extension.js
+++ b/bowser-gnome@kronosoul.xyz/extension.js
@@ -213,7 +213,7 @@ function openBrowser(overrideURI) {
         util.spawn(argv);
         Me.URIs.shift();
     }
-    } catch(e) { dev.log(e); }
+    } catch(e) { dev.log(e); Me.URIs.shift(); }
 }
 function spawnUnmatchedURIDialog() {
     // Parse the URI list in sequential dialogs
```

**Comment by blipk** [comment]
Is this tested as resolving the issue for you?

**Comment by blipk** [comment]
Pushed another fix that should resolve this.

**Comment by pdecat** [comment]
> Pushed another fix that should resolve this.

Fix confirmed to work for me, thanks!

**Pull request closed without merging**
